# Site settings
title: Franck Lab
email: john.m.franck@acertcenter.org
description: > # this means to ignore newlines until "baseurl:"
    ©2023 J.M. Franck
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmfrancklab.github.io" # the base hostname & protocol for your site
#url: "http://symposium2015.acert.cornell.edu" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  jmfranck
# Build settings
markdown: kramdown
#markdown: redcarpet
VMs_available: True
assets:
    sources:
        - assets/

plugins:
    - jekyll-scholar

scholar:
    style: edited-pmid-format.csl
    locale: en
    source: .
    bibliography: references.bib
    bibliography_template: bibliography
    sort_by: none
    order: ascending
