#!/bin/bash
echo "generate bib file by running pandoc:"
echo "pandoc AAResearch_citations.md --biblatex --standalone -o AAResearch_citations.tex"
echo "then generate from aux using jabref (and abbreviate)"
pandoc citeproc_src/AAResearch_citations.md -f markdown -t markdown-citations --citeproc --csl=edited-pmid-format.csl --bibliography references.bib -o AAResearch.md
# add the header, which gets omitted
{ head -5 citeproc_src/AAResearch_citations.md; echo; echo "<!--DO NOT EDIT this file directly - edit the corresponding file in citeproc_src-->"; echo; cat AAResearch.md; } > AAResearch.md.new
mv AAResearch.md.new AAResearch.md
sed -i 's/\^\([0-9,\\-]\+\)\^/<sup>\1<\/sup>/g' AAResearch.md
sed -i 's/~\([^~]\{0,10\}\)~/<sub>\1<\/sub>/g' AAResearch.md
sed -i '/^::: *$/d' AAResearch.md
sed -i '/^::: {#ref/d' AAResearch.md
sed -i 's/{#references-[^}]*}//' AAResearch.md
